N0vice17/DataStructures-And-Algorithm

- LinkedList/Problems/README.md
- LinkedList/Problems/addNumbersLeetcode.java
I have added a Problem on Singly Linked List.
I have also provided the solution to the said problem.
Note: Code(s) have been written in JAVA.
> Added Problem on Singly Linked List

- LinkedList/FloydCycleDetection.java
Contributing a code to implement Floyd's Cycle Detection. 
The code contains 2 methods:
- detectLoop() : To detect the presence of a loop in a Singly Linked List
- startingNodeOfLoop() : To return the node from which the loop is starting.
The code is written in JAVA.
> Floyd's Cycle Detection

- C++ Data Structures OOP/Binary Search Tree/README.md
- C++ Data Structures OOP/Binary Search Tree/checkBSTorNOT.cpp
- C++ Data Structures OOP/Binary Search Tree/findHeight.cpp
- C++ Data Structures OOP/Binary Search Tree/findMinMaxFromBST.cpp
- C++ Data Structures OOP/Binary Search Tree/implementBST.cpp
- C++ Data Structures OOP/Binary Search Tree/treeTraversal.cpp
- C++ Data Structures OOP/Linked List/README.md
- C++ Data Structures OOP/Linked List/doublyLinkedList.cpp
- C++ Data Structures OOP/Linked List/singlyCIrcularLinkedList.cpp
- C++ Data Structures OOP/Linked List/singlyLinkedList.cpp
- C++ Data Structures OOP/Queue/README.md
- C++ Data Structures OOP/Queue/arrayImplementation.cpp
- C++ Data Structures OOP/Queue/linkedListImplementation.cpp
- C++ Data Structures OOP/README.md
- C++ Data Structures OOP/Stack/README.md
- C++ Data Structures OOP/Stack/arrayImplementation.cpp
- C++ Data Structures OOP/Stack/checkBalancedParentheses.cpp
- C++ Data Structures OOP/Stack/evaluatePostfix.cpp
- C++ Data Structures OOP/Stack/evaluatePrefix.cpp
- C++ Data Structures OOP/Stack/infixToPostfix.cpp
- C++ Data Structures OOP/Stack/linkedListImplementation.cpp
- README.md
This directory includes Object Oriented implementation of popular Data Structures in C++. Implementing data structures in an object-oriented programming (OOP) style promotes encapsulation, enhancing code reusability, maintainability, and modularity.
Also added a new line in README.md file knowing about the newly added directory.
> Added a directory titled "C++ Data Structures OOP"

- Queue/BinaryNumbersUsingQueue.java
This PR contains the code for generating binary numbers from 1 to n using a Queue.
> Binary Number using Queue

- LinkedList/C/linkedList.c
- LinkedList/C/linkedList.h
- LinkedList/C/main.c
- README.md
- Stack/C/array based implementation/main.c
- Stack/C/array based implementation/stack.c
- Stack/C/array based implementation/stack.h
- Stack/C/linked list based implementation/main.c
- Stack/C/linked list based implementation/stack.c
- Stack/C/linked list based implementation/stack.h
In this type of implementation, the code is divided into 3 files.
1st is the header file which contains the function declarations and macro definitions.
2nd is the implementation where all the functions are implemented.
3rd is the driver code.
> Add opaque pointer implementation of linkedlist and stack in C language and update README.md

- Stack/JAVA/Tower_of_Hanoi.java
Added Tower of Hanoi program code in java
> added-Tower_of_Hanoi

- Sorting_Algorithm/PYTHON/selectionSort.py
This PR is with reference to Issue #20 
I have added a Python code for implementing Selection Sort.
> Implement Selection Sort

- Tree/C++/BinaryTree/BinaryTree.cpp
- Tree/C++/BinaryTree/BoundryTraversal.cpp
Attempt to Resolve issue no. #21 .
> Added binary tree folder

- Sorting_Algorithm/PYTHON/bubbleSort.py
- Sorting_Algorithm/PYTHON/selectionSort.py
This PR is with reference to Issue #20 . 
I have implemented Bubble sort using Python.
> Implement Bubble Sort in Python

- LinkedList/python/Double LinkedList_combined.py
Added Double linkedlist problem in python
> Double_Linked_list in python

- Searching_Algorithm/PYTHON/BinarySearch_UsingRecursion.py
Implementing Binary Search using Recursion in Python
> Feat: Implement Recursive Binary Search in Python

- Stack/JAVA/StackUsingArrayList.java
- Stack/JAVA/StackUsingQueue.java
stack implementation using ArrayList and Queue
> added stack implementation

- Some_important_algos/AllPalindromicPermutations.java
I have added a new algorithm for finding all the palindromic permutations of a string in java..
I request you to kindly review and merge this algo.
> Added AllPalindromicPermutations in Some_Important_algos

- Sorting_Algorithm/JAVA/RadixSort.java
I have added RadixSort Code in Java. I request Agnik7 or N0vice17 to review my changes.
> Added RadixSort

- Queue/JAVA/QueueUsingArrayList.java
- Queue/JAVA/QueueUsingStack.java
queue implementation using ArrayList and Stack
> added queue implementation

- Queue/C/ArrayImplementation.h
- Queue/C/Arrayimplementation.c
Array implementation of queue in C
> Implement C queue

- Stack/JAVA/BasicStack.java
- Stack/JAVA/CustomStack.java
- Stack/JAVA/DynamicStack.java
> Ways to different stack!

- LinkedList/JAVA/InsertGCDInLinkedList.java
- LinkedList/JAVA/IntersectionOfTwoLinkedLists.java
Added solutions to the following problems to the repo. All the solutions have been added in Java
* Intersection of 2 Linked Lists
* Insert GCD between Nodes of a Linked List
This PR is in response to issue #20
> Add solutions to 2 problems on Linked List

- LinkedList/python/Double_Circular_Linkedlist.py
Added a Double_Circular_Linkedlist problem solution in python. Circular Doubly Linked List is a linear data structure which consists of nodes. Each node is divided into three parts containing data part, pointer to previous node and pointer to next node.Unlike Linked List or Doubly Linked List, Circular Doubly Linked List doesn't contain NULL values in any of the nodes rather the head's previous pointer points to last node and last node's next pointer points to head.
Please review and merge the code.
> Double_Circular_Linkedlist in python

- Recursion/N_Queens.py
- Recursion/Sudoko_solver.py
I added a new folder recursion in which i added Nqueens and Sudokosolver in python.
I'm currently in my 100daysofcodechallenge can check in my linkedin 
[https://www.linkedin.com/in/sai-sree-ram-chavali-575788257/](url)
so i wish i could contribute all the questions i'm solving here in python 
😊
> added Nqueens and sudokosolver

- Tree/JAVA/ verticalOrderTraversal.java
Added a solution for a very popular hard problem named as vertical order traversal of binary tree
> vertical order traversal of a binary tree

- Tree/C++/avlTree.cpp
I have added AVL Tree data structure which is a self balancing Tree.
- for inserting - Insert()
- for deleting - Deletenode()
- for traversal - LevelOrder()
All functions are made
> added AVL Tree

- Sorting_Algorithm/C/bubble_sort.c
- Sorting_Algorithm/C/insertion_sort.c
- Sorting_Algorithm/C/selection_sort.c
This pull request adds C implementations of three common sorting algorithms: 
Bubble Sort, Selection Sort, and Insertion Sort
@IndranjanaChatterjee  @N0vice17    I would greatly appreciate it if you could take some time to review my pull request. Your feedback and suggestions would be very valuable. Thank you!
> Add Sorting algorithms  (C language)

- LinkedList/C++/palindrome check in linkedlist
write a c++ code to check whether a linkedlist is palindrome or not
> Create palindrome check in linkedlist

- Stack/JAVA/KnapSackTopDown.java
I have added the code for the knapsack top down approach using dynamic programing in java programming language
> Added Knap Sack Top Down Approach using Dynamic Programming in Java

- Tree/JAVA/MaxHeapImp.java
I added an implementation for Max heap in java, (although we can use a priority queue to work with max heap in Java but for better understanding and illustration of this DS I added an implementation for it in java under Tree/JAVA folder)
> feat: add Max heap imp java

- Sorting_Algorithm/PYTHON/quickSort.py
added the quicksort algorithm code in Python3
> Adding Quicksort Algorithm in Python

- Graphs/Kosaraju’s_Algo.java
@N0vice17 Please review the changes and accept my pull request
> Add Kosaraju's Algo

- Some_important_algos/Anagram.java
An anagram is a word or phrase formed by rearranging the letters of another word or phrase, using all the original letters exactly once.
> Added Anagram Code in Java

- Sorting_Algorithm/PYTHON/MergeSort.py
Fix: Issue #20 Hactoberfest2023 MergeSort.py
> issue #20 Create MergeSort.py

- LinkedList/C/doubly_linked_list.c
Added doubly linked list using c inside linked list folder.
In this i have done all the operations like create,delete,split ,merge and display.
If the code is okay can you please merge the request and add hacktoberfest-accepeted label to the request.
> doubly linked list added

- Stack/PYTHON/Queue_using_Stack.py
- Stack/PYTHON/Stack_using_Queue.py
Added a new sub folder under stack folder named python
> Implemented stack using queue and queue using stack in python

- Searching_Algorithm/C/Interpolation_search.c
Added Interpolation_search in C language. Please review and merge..
Thank you
> [ADD]:Interpolation_search

- Sorting_Algorithm/C/combo_search_sort.c
i have added linear search,binary search,bubble sort,selection sort,insertion sort ,quick sort as well as merge sort combo program within sorting algorithm folder inside c folder.
If the code is okay and can you please merge the request and add hactoberfest-accepted label to the request.
> added searching and sorting combo algos

- Sorting_Algorithm/JAVA/Cycle_sort.java
Added Cycle sort which was missing in the Sorting Algorithms.
> Added cycle sort

- LinkedList/C/Add-two-polynomials-using-linked-list.c
- LinkedList/C/Circular-Linked-List.c
I have added two linked list files in the LinkedList folder in C Language.
> Added two linked list files 

- Tree/JAVA/RangeSumOfBST.java
I have added code for Sum of BST for a particular given range. Please merge PR :)!
> Sum Of BST

- LinkedList/python/Rotate_Linkedlist.py
Added program to rotate the elements of a LinkedList in python
> Rotating elements of a LinkedList
